// Game draw: teams playing and clubs on Boundary / Timekeeping / Scoring duty, keyed day|time|field.
// PLACEHOLDER — generated by tools/make_placeholder_games.py. Replace with the real draw when released.
window.GAMES = {
 "placeholder": true,
 "games": {
  "sat|9am|1": {
   "div": "MD2",
   "home": "Kansas City Power",
   "away": "Rome Redbacks",
   "boundary": "Seattle Grizzlies",
   "timekeeper": "Seattle Grizzlies",
   "scorer": "Seattle Grizzlies"
  },
  "sat|9am|2": {
   "div": "WD1",
   "home": "Baton Rouge Tigers",
   "away": "Denver Bulldogs",
   "boundary": "North Texas Devils",
   "timekeeper": "North Texas Devils",
   "scorer": "North Texas Devils"
  },
  "sat|9am|3": {
   "div": "MD1",
   "home": "Milwaukee Bombers",
   "away": "St Louis Blues",
   "boundary": "Sacramento Suns",
   "timekeeper": "Sacramento Suns",
   "scorer": "Sacramento Suns"
  },
  "sat|10am|1": {
   "div": "WD1",
   "home": "Austin Crows",
   "away": "Charlotte Blue Heelers",
   "boundary": "Philadelphia Hawks",
   "timekeeper": "Philadelphia Hawks",
   "scorer": "Philadelphia Hawks"
  },
  "sat|10am|2": {
   "div": "MD5",
   "home": "Louisville Kings",
   "away": "Des Moines Roosters",
   "boundary": "New York Magpies",
   "timekeeper": "New York Magpies",
   "scorer": "New York Magpies"
  },
  "sat|10am|3": {
   "div": "WD1",
   "home": "Atlanta Kookaburras",
   "away": "Arizona Hawks",
   "boundary": "Dallas Dingoes",
   "timekeeper": "Dallas Dingoes",
   "scorer": "Dallas Dingoes"
  },
  "sat|10am|4": {
   "div": "MD5",
   "home": "Boston Demons",
   "away": "Birmingham Bushrangers",
   "boundary": "Seattle Grizzlies",
   "timekeeper": "Seattle Grizzlies",
   "scorer": "Seattle Grizzlies"
  },
  "sat|10am|5": {
   "div": "MD3",
   "home": "Golden Gate Roos",
   "away": "Cincinnati Dockers",
   "boundary": "Tampa Bay Tiger Sharks",
   "timekeeper": "Tampa Bay Tiger Sharks",
   "scorer": "Tampa Bay Tiger Sharks"
  },
  "sat|11am|1": {
   "div": "MD4",
   "home": "Arizona Hawks",
   "away": "Denver Bulldogs",
   "boundary": "Seattle Grizzlies",
   "timekeeper": "Seattle Grizzlies",
   "scorer": "Seattle Grizzlies"
  },
  "sat|11am|2": {
   "div": "MD3",
   "home": "Savannah Hurricanes",
   "away": "Sacramento Suns",
   "boundary": "Boston Demons",
   "timekeeper": "Boston Demons",
   "scorer": "Boston Demons"
  },
  "sat|11am|3": {
   "div": "MD5",
   "home": "Oklahoma Buffaloes",
   "away": "Louisville Kings",
   "boundary": "Dallas Dingoes",
   "timekeeper": "Dallas Dingoes",
   "scorer": "Dallas Dingoes"
  },
  "sat|11am|4": {
   "div": "MD4",
   "home": "Nashville Kangaroos",
   "away": "Baltimore Dockers",
   "boundary": "Jacksonville Saints",
   "timekeeper": "Jacksonville Saints",
   "scorer": "Jacksonville Saints"
  },
  "sat|11am|5": {
   "div": "MD3",
   "home": "San Diego Lions",
   "away": "North Carolina Tigers",
   "boundary": "Orange County Giants",
   "timekeeper": "Orange County Giants",
   "scorer": "Orange County Giants"
  },
  "sat|12pm|1": {
   "div": "WD1",
   "home": "St Louis Blues",
   "away": "Atlanta Kookaburras",
   "boundary": "Minnesota Freeze",
   "timekeeper": "Minnesota Freeze",
   "scorer": "Minnesota Freeze"
  },
  "sat|12pm|2": {
   "div": "MD1",
   "home": "St Louis Blues",
   "away": "Austin Crows",
   "boundary": "Fort Lauderdale Fighting Squids",
   "timekeeper": "Fort Lauderdale Fighting Squids",
   "scorer": "Fort Lauderdale Fighting Squids"
  },
  "sat|12pm|3": {
   "div": "WD1",
   "home": "Philadelphia Hawks",
   "away": "Chicago Swans",
   "boundary": "Wisconsin Wombats",
   "timekeeper": "Wisconsin Wombats",
   "scorer": "Wisconsin Wombats"
  },
  "sat|1pm|1": {
   "div": "MD3",
   "home": "Atlanta Kookaburras",
   "away": "Minnesota Freeze",
   "boundary": "Indianapolis Giants",
   "timekeeper": "Indianapolis Giants",
   "scorer": "Indianapolis Giants"
  },
  "sat|1pm|2": {
   "div": "MD5",
   "home": "Louisville Kings",
   "away": "Fort Lauderdale Fighting Squids",
   "boundary": "Rome Redbacks",
   "timekeeper": "Rome Redbacks",
   "scorer": "Rome Redbacks"
  },
  "sat|1pm|3": {
   "div": "WD1",
   "home": "Philadelphia Hawks",
   "away": "Minnesota Freeze",
   "boundary": "Portland",
   "timekeeper": "Portland",
   "scorer": "Portland"
  },
  "sat|1pm|4": {
   "div": "WD1",
   "home": "Golden Gate Roos",
   "away": "North Texas Devils",
   "boundary": "Chicago Swans",
   "timekeeper": "Chicago Swans",
   "scorer": "Chicago Swans"
  },
  "sat|2pm|1": {
   "div": "MD5",
   "home": "Oklahoma Buffaloes",
   "away": "Birmingham Bushrangers",
   "boundary": "Maine Cats",
   "timekeeper": "Maine Cats",
   "scorer": "Maine Cats"
  },
  "sat|2pm|2": {
   "div": "MD2",
   "home": "Rome Redbacks",
   "away": "Wilmington Bombers",
   "boundary": "Los Angeles Dragons",
   "timekeeper": "Los Angeles Dragons",
   "scorer": "Los Angeles Dragons"
  },
  "sat|2pm|3": {
   "div": "WD1",
   "home": "Portland",
   "away": "St Louis Blues",
   "boundary": "Baltimore Dockers",
   "timekeeper": "Baltimore Dockers",
   "scorer": "Baltimore Dockers"
  },
  "sat|2pm|4": {
   "div": "MD3",
   "home": "Minnesota Freeze",
   "away": "North Carolina Tigers",
   "boundary": "San Diego Lions",
   "timekeeper": "San Diego Lions",
   "scorer": "San Diego Lions"
  },
  "sat|2pm|5": {
   "div": "MD3",
   "home": "Savannah Hurricanes",
   "away": "Cincinnati Dockers",
   "boundary": "Chicago Swans",
   "timekeeper": "Chicago Swans",
   "scorer": "Chicago Swans"
  },
  "sat|3pm|1": {
   "div": "MD4",
   "home": "Houston Lonestars",
   "away": "Virginia Lions",
   "boundary": "Chicago Swans",
   "timekeeper": "Chicago Swans",
   "scorer": "Chicago Swans"
  },
  "sat|3pm|2": {
   "div": "MD2",
   "home": "Wisconsin Wombats",
   "away": "North Texas Devils",
   "boundary": "New York Magpies",
   "timekeeper": "New York Magpies",
   "scorer": "New York Magpies"
  },
  "sat|3pm|3": {
   "div": "MD1",
   "home": "St Louis Blues",
   "away": "Milwaukee Bombers",
   "boundary": "Austin Crows",
   "timekeeper": "Austin Crows",
   "scorer": "Austin Crows"
  },
  "sat|3pm|5": {
   "div": "WD1",
   "home": "Arizona Hawks",
   "away": "Minnesota Freeze",
   "boundary": "Savannah Hurricanes",
   "timekeeper": "Savannah Hurricanes",
   "scorer": "Savannah Hurricanes"
  },
  "sat|4pm|1": {
   "div": "MD1",
   "home": "Milwaukee Bombers",
   "away": "Austin Crows",
   "boundary": "North Carolina Tigers",
   "timekeeper": "North Carolina Tigers",
   "scorer": "North Carolina Tigers"
  },
  "sat|4pm|2": {
   "div": "MD1",
   "home": "Maine Cats",
   "away": "Chicago Swans",
   "boundary": "Portland",
   "timekeeper": "Portland",
   "scorer": "Portland"
  },
  "sat|4pm|3": {
   "div": "WD1",
   "home": "North Texas Devils",
   "away": "Minnesota Freeze",
   "boundary": "Dallas Dingoes",
   "timekeeper": "Dallas Dingoes",
   "scorer": "Dallas Dingoes"
  },
  "sat|4pm|4": {
   "div": "MD4",
   "home": "Denver Bulldogs",
   "away": "Arizona Hawks",
   "boundary": "Boston Demons",
   "timekeeper": "Boston Demons",
   "scorer": "Boston Demons"
  },
  "sat|5pm|1": {
   "div": "MD2",
   "home": "North Texas Devils",
   "away": "Grovetown Pirates",
   "boundary": "Finger Lakes Blue Herons",
   "timekeeper": "Finger Lakes Blue Herons",
   "scorer": "Finger Lakes Blue Herons"
  },
  "sat|5pm|2": {
   "div": "MD4",
   "home": "Los Angeles Dragons",
   "away": "Orange County Giants",
   "boundary": "Cleveland Cannons",
   "timekeeper": "Cleveland Cannons",
   "scorer": "Cleveland Cannons"
  },
  "sat|5pm|3": {
   "div": "MD4",
   "home": "Baltimore Dockers",
   "away": "Las Vegas Gamblers",
   "boundary": "St Louis Blues",
   "timekeeper": "St Louis Blues",
   "scorer": "St Louis Blues"
  },
  "sun|9am|1": {
   "div": "MD3",
   "home": "San Diego Lions",
   "away": "Golden Gate Roos",
   "boundary": "Denver Bulldogs",
   "timekeeper": "Denver Bulldogs",
   "scorer": "Denver Bulldogs"
  },
  "sun|9am|2": {
   "div": "WD1",
   "home": "Seattle Grizzlies",
   "away": "Austin Crows",
   "boundary": "Las Vegas Gamblers",
   "timekeeper": "Las Vegas Gamblers",
   "scorer": "Las Vegas Gamblers"
  },
  "sun|9am|3": {
   "div": "MD2",
   "home": "Kansas City Power",
   "away": "North Texas Devils",
   "boundary": "Cleveland Cannons",
   "timekeeper": "Cleveland Cannons",
   "scorer": "Cleveland Cannons"
  },
  "sun|9am|4": {
   "div": "MD5",
   "home": "Birmingham Bushrangers",
   "away": "Charlotte Blue Heelers",
   "boundary": "Cincinnati Dockers",
   "timekeeper": "Cincinnati Dockers",
   "scorer": "Cincinnati Dockers"
  },
  "sun|9am|5": {
   "div": "MD3",
   "home": "Sacramento Suns",
   "away": "North Carolina Tigers",
   "boundary": "Houston Lonestars",
   "timekeeper": "Houston Lonestars",
   "scorer": "Houston Lonestars"
  },
  "sun|10am|1": {
   "div": "MD5",
   "home": "Oklahoma Buffaloes",
   "away": "Birmingham Bushrangers",
   "boundary": "Chicago Swans",
   "timekeeper": "Chicago Swans",
   "scorer": "Chicago Swans"
  },
  "sun|10am|2": {
   "div": "WD1",
   "home": "Boston Demons",
   "away": "Cincinnati Dockers",
   "boundary": "Denver Bulldogs",
   "timekeeper": "Denver Bulldogs",
   "scorer": "Denver Bulldogs"
  },
  "sun|10am|3": {
   "div": "WD1",
   "home": "Seattle Grizzlies",
   "away": "Bayou Brawlers",
   "boundary": "Wisconsin Wombats",
   "timekeeper": "Wisconsin Wombats",
   "scorer": "Wisconsin Wombats"
  },
  "sun|10am|4": {
   "div": "MD5",
   "home": "Des Moines Roosters",
   "away": "Fort Lauderdale Fighting Squids",
   "boundary": "Wasatch WarGulls",
   "timekeeper": "Wasatch WarGulls",
   "scorer": "Wasatch WarGulls"
  },
  "sun|10am|5": {
   "div": "MD3",
   "home": "Savannah Hurricanes",
   "away": "Atlanta Kookaburras",
   "boundary": "Los Angeles Dragons",
   "timekeeper": "Los Angeles Dragons",
   "scorer": "Los Angeles Dragons"
  },
  "sun|11am|1": {
   "div": "WD1",
   "home": "Sacramento Suns",
   "away": "Golden Gate Roos",
   "boundary": "Finger Lakes Blue Herons",
   "timekeeper": "Finger Lakes Blue Herons",
   "scorer": "Finger Lakes Blue Herons"
  },
  "sun|11am|2": {
   "div": "MD1",
   "home": "Philadelphia Hawks",
   "away": "Dallas Dingoes",
   "boundary": "Fort Lauderdale Fighting Squids",
   "timekeeper": "Fort Lauderdale Fighting Squids",
   "scorer": "Fort Lauderdale Fighting Squids"
  },
  "sun|11am|3": {
   "div": "WD1",
   "home": "Boston Demons",
   "away": "Minnesota Freeze",
   "boundary": "Savannah Hurricanes",
   "timekeeper": "Savannah Hurricanes",
   "scorer": "Savannah Hurricanes"
  },
  "sun|11am|4": {
   "div": "MD3",
   "home": "Bayou Brawlers",
   "away": "Portland",
   "boundary": "Wisconsin Wombats",
   "timekeeper": "Wisconsin Wombats",
   "scorer": "Wisconsin Wombats"
  },
  "sun|12pm|1": {
   "div": "MD5",
   "home": "Jacksonville Saints",
   "away": "Des Moines Roosters",
   "boundary": "Indianapolis Giants",
   "timekeeper": "Indianapolis Giants",
   "scorer": "Indianapolis Giants"
  },
  "sun|12pm|2": {
   "div": "MD5",
   "home": "Boston Demons",
   "away": "Oklahoma Buffaloes",
   "boundary": "Wilmington Bombers",
   "timekeeper": "Wilmington Bombers",
   "scorer": "Wilmington Bombers"
  },
  "sun|12pm|3": {
   "div": "MD3",
   "home": "Portland",
   "away": "Cincinnati Dockers",
   "boundary": "Minnesota Freeze",
   "timekeeper": "Minnesota Freeze",
   "scorer": "Minnesota Freeze"
  },
  "sun|12pm|4": {
   "div": "WD1",
   "home": "Arizona Hawks",
   "away": "Golden Gate Roos",
   "boundary": "Orange County Giants",
   "timekeeper": "Orange County Giants",
   "scorer": "Orange County Giants"
  },
  "sun|12pm|5": {
   "div": "MD3",
   "home": "Sacramento Suns",
   "away": "Golden Gate Roos",
   "boundary": "Los Angeles Dragons",
   "timekeeper": "Los Angeles Dragons",
   "scorer": "Los Angeles Dragons"
  },
  "sun|1pm|2": {
   "div": "MD1",
   "home": "Columbus Cats",
   "away": "Chicago Swans",
   "boundary": "Jacksonville Saints",
   "timekeeper": "Jacksonville Saints",
   "scorer": "Jacksonville Saints"
  },
  "sun|1pm|4": {
   "div": "MD1",
   "home": "Milwaukee Bombers",
   "away": "Dallas Dingoes",
   "boundary": "Sacramento Suns",
   "timekeeper": "Sacramento Suns",
   "scorer": "Sacramento Suns"
  },
  "finals|2pm|3": {
   "div": "WD1",
   "home": "North Texas Devils",
   "away": "Philadelphia Hawks",
   "boundary": "Boston Demons",
   "timekeeper": "Boston Demons",
   "scorer": "Boston Demons"
  },
  "finals|4:30pm|1": {
   "div": "WD1",
   "home": "Baton Rouge Tigers",
   "away": "Columbus Cats",
   "boundary": "Sacramento Suns",
   "timekeeper": "Sacramento Suns",
   "scorer": "Sacramento Suns"
  }
 }
};
