#!/usr/bin/env python3
"""Generate a PLACEHOLDER game draw (games.js) for every field that has umpires assigned.

Usage: python3 tools/make_placeholder_games.py > games.js

Club names come from aussierulesusa.com/clubs. Each club is placed in a division
(men's MD1-MD5, one women's division WD1); each game is two teams from the same division, plus a club on Boundary / Timekeeping / Scoring duty.
Within any hour, no club plays twice and the duty club isn't playing that hour.
Replace games.js with the real draw once the fixture is released (same shape).
"""
import json
import random
import re

MENS = [
    "Arizona Hawks", "Atlanta Kookaburras", "Austin Crows", "Baltimore Dockers", "Baton Rouge Tigers", "Bayou Brawlers",
    "Birmingham Bushrangers", "Boston Demons", "Charlotte Blue Heelers", "Chicago Swans", "Cincinnati Dockers",
    "Cleveland Cannons", "Columbus Cats", "Dallas Dingoes", "Denver Bulldogs", "Des Moines Roosters",
    "Finger Lakes Blue Herons", "Fort Lauderdale Fighting Squids", "Golden Gate Roos", "Grovetown Pirates",
    "Houston Lonestars", "Indianapolis Giants", "Jacksonville Saints", "Kansas City Power", "Las Vegas Gamblers",
    "Los Angeles Dragons", "Louisville Kings", "Maine Cats", "Milwaukee Bombers", "Minnesota Freeze",
    "Nashville Kangaroos", "New York Magpies", "North Carolina Tigers", "North Texas Devils", "Oklahoma Buffaloes",
    "Omaha Outbacks", "Orange County Giants", "Philadelphia Hawks", "Portland", "Rome Redbacks", "Sacramento Suns",
    "St Louis Blues", "San Diego Lions", "Savannah Hurricanes", "Seattle Grizzlies", "Tampa Bay Tiger Sharks",
    "Virginia Lions", "Wasatch WarGulls", "Wilmington Bombers", "Wisconsin Wombats",
]
WOMENS = [
    "Arizona Hawks", "Atlanta Kookaburras", "Austin Crows", "Baton Rouge Tigers", "Bayou Brawlers", "Boston Demons",
    "Charlotte Blue Heelers", "Chicago Swans", "Cincinnati Dockers", "Columbus Cats", "Denver Bulldogs",
    "Golden Gate Roos", "Houston Lonestars", "Minnesota Freeze", "New York Magpies", "North Star Blue Ox",
    "North Texas Devils", "Orange County Giants", "Philadelphia Hawks", "Portland", "Sacramento Suns",
    "St Louis Blues", "Seattle Grizzlies", "Virginia Lions", "Wasatch WarGulls",
]
ON_FIELD = {"field", "goal", "boundary", "ts"}
MENS_DIVS = ["MD1", "MD2", "MD3", "MD4", "MD5"]
WOMENS_DIVS = ["WD1"]  # single women's division


def main():
    src = open("data.js").read()
    umpires = json.loads(re.search(r"window\.UMPIRES = (.*?);\nwindow\.SLOT_ORDER", src, re.S).group(1))
    order = json.loads(re.search(r"window\.SLOT_ORDER = (.*?);", src).group(1))

    # every (day, time, field) that has at least one umpire on it
    busy = {}
    for u in umpires:
        for s in u["slots"]:
            if s["type"] in ON_FIELD and s.get("field"):
                busy.setdefault((s["day"], s["time"]), set()).add(s["field"])

    rng = random.Random(2026)  # fixed seed: same placeholder draw every run
    # give every club a division: men's MD1-MD5, women's WD1; games are within a division
    div_of = {}
    for clubs, divs in ((MENS, MENS_DIVS), (WOMENS, WOMENS_DIVS)):
        shuffled = clubs[:]
        rng.shuffle(shuffled)
        for i, c in enumerate(shuffled):
            div_of[(divs[0][0], c)] = divs[i % len(divs)]
    teams = {d: [c for (g, c), dv in div_of.items() if dv == d] for d in MENS_DIVS + WOMENS_DIVS}

    games = {}
    for slot in order:
        key = (slot["day"], slot["time"])
        if key not in busy:
            continue
        used = set()  # clubs playing or on duty this hour (a club's men's and women's sides count separately)
        for field in sorted(busy[key]):
            divs = WOMENS_DIVS if rng.random() < 0.3 else MENS_DIVS
            options = [d for d in divs if len([c for c in teams[d] if (d[0], c) not in used]) >= 2]
            div = rng.choice(options)
            home, away = rng.sample([c for c in teams[div] if (div[0], c) not in used], 2)
            used.update(((div[0], home), (div[0], away)))
            duty = rng.choice([c for c in MENS if ("M", c) not in used and ("W", c) not in used])
            used.update((("M", duty), ("W", duty)))  # whole club is busy on duty
            games[f"{slot['day']}|{slot['time']}|{field}"] = {
                "div": div, "home": home, "away": away,
                "boundary": duty, "timekeeper": duty, "scorer": duty,
            }

    print("// Game draw: teams playing and clubs on Boundary / Timekeeping / Scoring duty, keyed day|time|field.")
    print("// PLACEHOLDER — generated by tools/make_placeholder_games.py. Replace with the real draw when released.")
    print("window.GAMES = " + json.dumps({"placeholder": True, "games": games}, indent=1) + ";")


if __name__ == "__main__":
    main()
